training:
  learning_rate: 2e-5
  num_epochs: 3
  batch_size: 16
  weight_decay: 0.01

data:
  train_file: "E:\\FINE_TUNNING\\datasets\\syamilah\\Splited\\A.csv"
  test_file: "E:\\FINE_TUNNING\\datasets\\syamilah\\Splited\\B.csv"

model:
  model_name: "aubmindlab/arabert"
  output_dir: "./models/arabic_sentence_transformer"
